<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ScreenRecorder.Core\ScreenRecorder.Core.csproj" />
    <ProjectReference Include="..\ScreenRecorder.Media\ScreenRecorder.Media.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.12" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
