<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ScreenRecorder.Core\ScreenRecorder.Core.csproj" />
    <ProjectReference Include="..\ScreenRecorder.Infrastructure\ScreenRecorder.Infrastructure.csproj" />
    <ProjectReference Include="..\ScreenRecorder.Media\ScreenRecorder.Media.csproj" />
    <ProjectReference Include="..\ScreenRecorder.Platform.Windows\ScreenRecorder.Platform.Windows.csproj" />
    <ProjectReference Include="..\ScreenRecorder.Platform.macOS\ScreenRecorder.Platform.macOS.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ScreenRecorder.Media.Tests" />
  </ItemGroup>

</Project>

