// SPDX-License-Identifier: AGPL-3.0-or-later
namespace ScreenRecorder.Core.Localization;

public class LocalizationService : ILocalizationService
{
    private static readonly Lazy<LocalizationService> _instance = new(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    private AppLanguage _currentLanguage = AppLanguage.ZhTw;

    public event EventHandler<AppLanguage>? LanguageChanged;

    public AppLanguage CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage != value)
            {
                _currentLanguage = value;
                LanguageChanged?.Invoke(this, value);
            }
        }
    }

    public string this[string key] => GetString(key);

    public string GetString(string key)
    {
        var dict = _currentLanguage == AppLanguage.ZhTw ? ZhTwDictionary : EnUsDictionary;
        if (dict.TryGetValue(key, out var val))
        {
            return val;
        }

        // Fallback to ZhTw
        if (ZhTwDictionary.TryGetValue(key, out var fallbackVal))
        {
            return fallbackVal;
        }

        return key;
    }

    public string GetFormatted(string key, params object[] args)
    {
        var template = GetString(key);
        try
        {
            return string.Format(template, args);
        }
        catch
        {
            return template;
        }
    }

    public static readonly Dictionary<string, string> ZhTwDictionary = new()
    {
        ["ProjectRestoreBackup"] = "從備份恢復",
        ["ProjectRestoreWarning"] = "將恢復到上一個有效存檔，較新的編輯可能不在備份中。受損原檔會另存保留，原始錄影素材不會刪除。是否繼續？",
        ["ProjectWorkspace"] = "錄影專案",
        ["ProjectPreview"] = "預覽",
        ["ProjectFrameLoading"] = "正在讀取影格…",
        ["ProjectFrameEmpty"] = "開啟有片段的專案以預覽",
        ["ProjectFrameUnavailable"] = "此位置無可用影格",
        ["ProjectStillPreview"] = "原始影格 · 尚不含效果／播放聲音",
        ["ProjectProperties"] = "片段屬性",
        ["ProjectTimeline"] = "時間軸",
        ["ProjectPreviewPending"] = "影片預覽尚未接線。目前可錄製、保存專案、重新開啟與續錄；這裡不顯示示範影片。",
        ["ProjectTimelinePending"] = "時間軸、縮圖與聲音波形尚未接線。原始素材會完整保留。",
        ["ProjectEntryHint"] = "保存素材，下次可接著錄；不必先輸出 MP4",
        ["ProjectNew"] = "新建專案",
        ["ProjectOpen"] = "開啟專案",
        ["ProjectSave"] = "儲存專案",
        ["ProjectClose"] = "關閉專案",
        ["ProjectRecord"] = "錄製新片段",
        ["ProjectContinue"] = "繼續錄製",
        ["ProjectPause"] = "暫停並保存",
        ["ProjectFinish"] = "結束本次錄製",
        ["ProjectCaptureSettings"] = "錄影設定",
        ["ProjectClips"] = "已保存的片段",
        ["ProjectClipLoadFailed"] = "片段資料不完整或已變更；請重新查詢後再編輯。",
        ["ProjectUndo"] = "復原",
        ["ProjectRedo"] = "重做",
        ["ProjectMoveEarlier"] = "往前移",
        ["ProjectSplit"] = "分割",
        ["ProjectGroupNext"] = "與下一段群組",
        ["ProjectUngroup"] = "解除群組",
        ["ProjectRangeStart"] = "範圍起點",
        ["ProjectRangeEnd"] = "範圍終點",
        ["ProjectDeleteRange"] = "刪除範圍",
        ["ProjectFitTimeline"] = "符合全段",
        ["ProjectWaveformLoading"] = "波形載入中…",
        ["ProjectWaveformUnavailable"] = "波形暫時無法載入",
        ["ProjectNoAudioTrack"] = "無音軌",
        ["ProjectTimelineHelp"] = "點時間尺定位；拖片段中間調整順序，拖兩側裁剪。滾輪平移，Ctrl／⌘＋滾輪縮放；Esc 取消。",
        ["ProjectMoveLater"] = "往後移",
        ["ProjectDeleteClip"] = "刪除片段",
        ["ProjectClipName"] = "片段名稱",
        ["ProjectAudioProperties"] = "聲音",
        ["ProjectVolume"] = "音量（%）",
        ["ProjectMute"] = "靜音",
        ["ProjectFadeIn"] = "淡入（秒）",
        ["ProjectFadeOut"] = "淡出（秒）",
        ["ProjectVideoProperties"] = "畫面",
        ["ProjectScale"] = "縮放（%）",
        ["ProjectCrop"] = "裁邊（%）",
        ["ProjectPositionX"] = "水平位移（%）",
        ["ProjectPositionY"] = "垂直位移（%）",
        ["ProjectApplyProperties"] = "套用調整",
        ["ProjectPropertyDraft"] = "請套用或取消調整，再切換片段。按儲存也會一併套用。",
        ["ProjectResetProperties"] = "取消調整",
        ["ProjectInvalidProperties"] = "請檢查片段名稱及數值；淡入淡出不可超過片段長度。",
        ["ProjectRename"] = "套用名稱",
        ["ProjectSourceSafe"] = "編輯不會改寫原始素材。儲存不會清除本次的復原／重做紀錄。",
        ["ProjectPhaseBNotice"] = "此階段提供保存、重開、續錄與名稱復原。時間軸裁剪、影片預覽和 MP4 輸出將於下一階段加入。重開專案不保留前次操作歷史。",
        ["ProjectRefresh"] = "重新查詢狀態",
        ["ProjectRecent"] = "最近專案",
        ["ProjectSaving"] = "處理及保存中…",
        ["ProjectSaved"] = "已儲存",
        ["ProjectSaveFailed"] = "操作未完成，請查看錯誤並重試",
        ["ProjectUnsaved"] = "尚未儲存",
        ["ProjectUnconfirmed"] = "錄影狀態尚未確認；請重新查詢，勿重複操作",
        ["ProjectFinishBeforeClose"] = "請先暫停或結束本次錄製並保存，再關閉專案。錄影不會因此中斷。",
        ["ProjectChooseFolder"] = "選擇專案存放資料夾",
        ["ProjectDefaultName"] = "錄影專案",
        ["ProjectModeClosed"] = "尚未開啟專案",
        ["ProjectModeReady"] = "準備就緒",
        ["ProjectModeRecording"] = "錄影中",
        ["ProjectModeSavingSegment"] = "正在保存片段",
        ["ProjectModePaused"] = "已暫停",
        ["ProjectModeSaveFailed"] = "片段保存失敗",
        ["ProjectModeInterrupted"] = "需要檢查素材或恢復備份",
        // 視窗標題與通用
        ["AppTitle"] = "OpenCam - 螢幕錄影工具",
        ["Confirm"] = "確認",
        ["Cancel"] = "取消",
        ["Close"] = "關閉",

        // 頂部控制列
        ["StartRecording"] = "開始錄影",
        ["StopRecording"] = "停止錄影",
        ["PauseRecording"] = "暫停",
        ["ResumeRecording"] = "繼續",
        ["OpenFolder"] = "開啟資料夾",
        ["Recovery"] = "修復救援",
        ["About"] = "關於",
        ["Language"] = "語言",
        ["TooltipStart"] = "開始螢幕錄影",
        ["TooltipStop"] = "安全結束錄製並無損封裝為 MP4",
        ["TooltipPause"] = "暫停錄影",
        ["TooltipResume"] = "繼續錄影",
        ["TooltipStartFormat"] = "開始螢幕錄影 [快捷鍵: {0}]",
        ["TooltipStopFormat"] = "安全結束錄製並無損封裝為 MP4 [快捷鍵: {0}]",
        ["TooltipPauseFormat"] = "暫停錄影 [快捷鍵: {0}]",
        ["TooltipResumeFormat"] = "繼續錄影 [快捷鍵: {0}]",
        ["TooltipFolder"] = "開啟錄影輸出資料夾 [快捷鍵: Ctrl+O]",
        ["TooltipRecovery"] = "掃描並無損轉出之前未正常結束的錄影檔案",
        ["TooltipAbout"] = "關於本程式、作者與第三方函式庫授權聲明 [快捷鍵: F1]",
        ["TooltipLanguage"] = "切換顯示語言 (Language)",

        // 準備中橫幅
        ["PreparingBanner"] = "正在初始化錄影管線與音訊捕捉，請稍候（錄影開始前請暫勿切換畫面）...",
        ["StartingBadge"] = "啟動中...",

        // 錄影目標摘要
        ["TargetFullScreen"] = "錄影目標：【全螢幕】",
        ["TargetMonitor"] = "錄影目標：【指定螢幕 - {0}】",
        ["TargetCustomRegion"] = "錄影目標：【自訂區域 - {0}x{1} (坐標 X:{2}, Y:{3})】",

        // 配置卡片
        ["ConfigTitle"] = "錄影配置",
        ["RangeTitle"] = "錄影範圍",
        ["RangeFullScreen"] = "全螢幕 (Full Screen)",
        ["RangeMonitor"] = "指定螢幕:",
        ["IdentifyDisplays"] = "辨識螢幕",
        ["IdentifyDisplaysTooltip"] = "在每個螢幕短暫顯示對應編號",
        ["DisplayIdentificationSelected"] = "目前選取",
        ["DisplayIdentificationIncomplete"] = "有 {0} 個螢幕無法可靠辨識；未顯示可能錯誤的編號。",
        ["RangeCustomRegion"] = "自訂矩形區域 (Custom Region)",
        ["AdjustRegion"] = "調整選區...",
        ["TooltipAdjustRegion"] = "點選以拖曳或縮放自訂錄影區域 [支援 Enter 確認與 ESC 取消]",
        ["FpsTitle"] = "幀率 (FPS):",
        ["AudioTitle"] = "音訊設定",
        ["AudioSystem"] = "錄製系統聲音",
        ["AudioSystemUnsupportedMac"] = "macOS 系統聲音（此版本尚未支援）",
        ["AudioMic"] = "錄製麥克風 (Microphone)",
        ["MicDevice"] = "麥克風設備:",
        ["StorageTitle"] = "儲存位置",
        ["ChangeFolder"] = "變更...",
        ["TooltipChangeFolder"] = "選擇其他錄影存放資料夾 [磁碟空間將即時切換]",

        // 狀態監控儀表板
        ["MonitorTitle"] = "錄影狀態監控",
        ["AudioMeterSystem"] = "系統聲音",
        ["AudioMeterMicrophone"] = "麥克風",
        ["AudioMeterOff"] = "未啟用",
        ["AudioMeterLive"] = "收音中",
        ["AudioMeterSilent"] = "無聲",
        ["AudioMeterPaused"] = "已暫停",
        ["AudioMeterUnavailable"] = "無法監測",
        ["StatusIdle"] = "待命中",
        ["StatusRecording"] = "錄影中",
        ["StatusPaused"] = "已暫停",
        ["StatusPreparing"] = "初始化中",
        ["FileSizeLabel"] = "已錄大小",
        ["DiskRemainingLabel"] = "磁碟剩餘",
        ["SafeContainerNotice"] = "MKV 連續安全寫入 · 停止自動無損 Remux MP4",

        // 狀態列動態訊息
        ["StatusReady"] = "準備就緒，點擊「開始錄影」即可錄製",
        ["StatusInitializing"] = "正在初始化錄影管線，請稍候並暫勿操作畫面...",
        ["StatusStartUnconfirmed"] = "尚無法確認錄影是否已開始；請保持程式開啟，或按「停止」安全結束。",
        ["StatusScreenPermissionRequired"] = "需要 macOS 螢幕錄製權限；請在「系統設定 → 隱私權與安全性 → 螢幕與系統音訊錄製」允許 OpenCam，然後重新啟動。",
        ["StatusRecordingActive"] = "正在錄影中 (安全工作容器 MKV 連續寫入)",
        ["StatusDiskSpaceWarning"] = "磁碟剩餘空間偏低：{0:F1} GB；低於危急門檻時將安全停止錄影",
        ["StatusRecorderHealthWarning"] = "錄影狀態異常：{0}",
        ["StatusRecorderStoppedUnexpectedly"] = "錄影異常中止：{0}",
        ["StatusPausedMsg"] = "錄影已暫停 (已保留前段內容)，點擊「繼續」繼續錄製",
        ["StatusResuming"] = "正在繼續錄影管線，請稍候...",
        ["StatusStopping"] = "正在安全關閉 MKV 並執行 MP4 無損封裝 (Remux)...",
        ["StatusSuccess"] = "錄影成功！已轉出 MP4 檔案",
        ["StatusFailed"] = "啟動失敗: {0}",
        ["StatusStopFailed"] = "停止失敗: {0}",
        ["StatusRecoverableDetected"] = "偵測到 {0} 個未正常結束之錄影工作階段！點擊「修復救援」即可一鍵轉出 MP4。",
        ["StatusNoRecoverable"] = "目前沒有需要救援的錄影工作階段。",
        ["StatusRecovering"] = "正在執行工作階段崩潰復原，請稍候...",
        ["StatusRecoverSuccess"] = "救援完成！成功救回 {0} 個工作階段並已無損轉為 MP4。",
        ["StatusRecoverPartial"] = "救援完成：完整救回 {0} 個、部分救回 {1} 個、失敗 {2} 個。部分救援可能缺少損壞的尾段，原始 MKV 均已保留。",
        ["StatusRecoverFailed"] = "救援失敗：{0} 個工作階段未能轉出。原始 MKV 仍已保留，請查看日誌。",
        ["StatusLocationUpdated"] = "儲存位置已更新為: {0}",
        ["StatusSetLocationFailed"] = "設定儲存目錄失敗: {0}",
        ["StatusOpenFolderFailed"] = "無法開啟儲存位置：{0}",
        ["StatusUnexpectedDisconnect"] = "錄影核心無預警中斷！已錄製內容已安全保留，可點擊「修復救援」轉出 MP4。",
        ["RecordingCloseWarningTitle"] = "錄影進行中",
        ["RecordingCloseWarningMessage"] = "目前正在錄影，請先停止錄影後再關閉程式。",
        ["RecordingCloseWarningDetail"] = "這次關閉要求已取消，OpenCam 會繼續錄影。",
        ["ReturnToRecording"] = "返回錄影",
        ["RecordingCloseUnconfirmedMessage"] = "錄影狀態尚未確認，且安全停止未成功。",
        ["RecordingCloseUnconfirmedDetail"] = "可保持程式開啟繼續等待；強制結束可能中斷影片，之後需使用修復救援。",
        ["ForceQuitButton"] = "強制結束…",
        ["ForceQuitConfirmTitle"] = "確認強制結束",
        ["ForceQuitConfirmMessage"] = "這會立即結束 OpenCam 與錄影程序，錄到一半的 MKV 可能需要修復救援。",
        ["ForceQuitConfirmDetail"] = "只有在安全停止失敗、錄影狀態無法確認時才使用。此動作無法復原。",
        ["ForceQuitCancel"] = "取消，保持開啟",
        ["ForceQuitConfirmAction"] = "確認強制結束",
        ["VersionAndAbout"] = "OpenCam {0} · 關於",

        // 關於視窗
        ["AboutTitle"] = "關於 OpenCam",
        ["AppName"] = "OpenCam",
        ["VersionLabel"] = "版本: {0}",
        ["AuthorLabel"] = "作者:",
        ["AuthorName"] = "鄭郁翰 (Yu-Han Cheng)",
        ["GithubLabel"] = "GitHub 專案首頁",
        ["ProjectLicenseLabel"] = "專案授權:",
        ["ProjectLicenseName"] = "AGPL-3.0-or-later",
        ["ProjectLicenseDetail"] = "OpenCam 原始碼依 GNU AGPL 第 3 版或更新版授權；完整條款及原始碼請見 GitHub 專案的 LICENSE 檔。無擔保提供。第三方元件各依其自身授權。",
        ["AppDescription"] = "一款簡單、穩定且具備極致可靠性的桌面螢幕錄影工具。\n核心特色包含：安全容器強制連續寫入、停止時無損轉碼 MP4、崩潰/斷電自動救援、支援多螢幕與自訂範圍、A/V 高精度同步。",
        ["ThirdPartyTitle"] = "主要第三方元件",
        ["LicenseFfmpegDesc"] = "官方套件使用啟用 GPL 元件（含 libx264）的 FFmpeg／ffprobe。確切授權版本、建置設定及原始碼資訊請見隨附聲明；不屬於 OpenCam 自有原始碼。",
        ["LicenseAvaloniaDesc"] = "The AvaloniaUI Project；上游授權文字：Copyright (c) AvaloniaUI OÜ。MIT License，並保留上游第三方聲明。",
        ["LicenseMvvmDesc"] = "Copyright (c) .NET Foundation and Contributors. 採用 MIT License 授權。",
        ["LicenseSerilogDesc"] = "Copyright (c) Serilog Contributors. 採用 Apache License 2.0 授權。",
        ["LicenseXunitDesc"] = "Copyright (c) .NET Foundation and Contributors. 採用 Apache License 2.0 授權。",
        ["LicenseOtherManagedDesc"] = "NAudio（Mark Heath）、MicroCom.Runtime（Nikita Tsukanov）、Tmds.DBus.Protocol（Tom Deseyn）與 Microsoft .NET／Extensions 元件：MIT；各元件完整版權見隨附聲明。",
        ["LicenseGraphicsDesc"] = "SkiaSharp／HarfBuzzSharp 的 .NET 包裝層：MIT。Skia、HarfBuzz、ANGLE 等原生元件另依各自條款，保留完整上游授權及聲明。",
        ["LicenseInterDesc"] = "Copyright 2020 The Inter Project Authors。隨 Avalonia.Fonts.Inter 提供的 Inter 3.019 字型：SIL Open Font License 1.1。",
        ["ThirdPartyNoticesDetail"] = "完整內容請見 THIRD-PARTY-NOTICES.md 及 third-party 資料夾（Windows：安裝目錄；macOS：App 內 Contents/Resources）。第三方元件保留各自授權，不因 OpenCam 採用 AGPL-3.0-or-later 而變更。",
        ["HotkeyCloseTip"] = "按 ESC 或 Enter 關閉",
        ["AboutReliabilityTitle"] = "核心可靠性架構 (Reliability First)",
        ["DisclaimerTitle"] = "免責聲明與使用條款",
        ["Disclaimer1Title"] = "1. 無保證條款：",
        ["Disclaimer1Text"] = "本軟體依「現狀」（AS IS）提供，不附任何明示或暗示之保證，包含但不限於商業適售性、特定用途之適用性、不侵權之保證。",
        ["Disclaimer2Title"] = "2. 風險自負：",
        ["Disclaimer2Text"] = "使用者應自行承擔使用本軟體之全部風險。",
        ["Disclaimer3Title"] = "3. 損害免責：",
        ["Disclaimer3Text"] = "對於本軟體導致之任何直接、間接、附帶、衍生性或懲罰性損害（含資料毀損、商業中斷、收益損失、商譽損害等），作者與貢獻者概不負責。",
        ["Disclaimer4Title"] = "4. 法規合規：",
        ["Disclaimer4Text"] = "涉及個人資料、敏感商業文件處理時，使用者應自行確保符合所在地之個人資料保護法、公司資安政策、以及相關法規（含我國個人資料保護法、營業秘密法）。",

        // 選區視窗
        ["RegionWindowTitle"] = "選擇錄影區域",
        ["RegionFitScreen"] = "滿版螢幕",
        ["TooltipRegionFitScreen"] = "快速將選取範圍貼齊放大至當前螢幕全螢幕",
        ["RegionConfirm"] = "確認選取 (Enter)",
        ["RegionCancel"] = "取消 (ESC)",
        ["RegionDragTip"] = "拖曳中間區域可平移選取範圍",
        ["RegionResizeTip"] = "拖曳四周邊框或四角錨點自由放大縮小 | 按下 ESC 取消 | Enter 或雙擊確認",
        ["RegionSizeFormat"] = "尺寸: {0} x {1} (坐標 X:{2}, Y:{3})",
        ["MonitorPrimaryFormat"] = "螢幕 {0} (主顯示器)",
        ["MonitorSecondaryFormat"] = "螢幕 {0} (副顯示器)",
        ["DefaultMicOption"] = "系統預設麥克風 (Default Microphone)",

        // 系統托盤與偏好設定
        ["MinimizeOnRecord"] = "開始錄影時自動最小化視窗",
        ["TrayShowWindow"] = "顯示主視窗",
        ["TrayStart"] = "開始錄影",
        ["TrayStop"] = "停止錄影",
        ["TrayExit"] = "結束程式",

        // 視訊編碼器與硬體加速
        ["EncoderTitle"] = "視訊編碼器:",
        ["EncoderAuto"] = "自動選擇 (優先硬體加速)",
        ["ActualEncoderPending"] = "實際編碼器：尚未決定",
        ["ActualCapturePending"] = "實際擷取：尚未決定",
        ["ActualCaptureFormat"] = "實際擷取：{0}",
        ["CaptureModeLabel"] = "Windows 畫面擷取",
        ["CaptureModeGdi"] = "相容擷取（GDI）",
        ["CaptureModeModern"] = "新版擷取（測試）",
        ["CaptureModeNotice"] = "嘗試改善部分電腦錄影時的游標閃爍；尚未保證修復。不支援的螢幕配置會使用 GDI，請查看實際擷取狀態。",
        ["CaptureFallbackFilter"] = "FFmpeg 未提供所需擷取能力",
        ["CaptureFallbackMapping"] = "無法安全對應螢幕",
        ["CaptureFallbackTopology"] = "此螢幕配置使用相容模式",
        ["CaptureFallbackStartup"] = "新版擷取啟動失敗，使用 GDI",
        ["ActualEncoderFormat"] = "實際編碼器：{0}",
        ["EncoderFallbackNoHardware"] = "未驗證到可用硬體",
        ["EncoderFallbackRequested"] = "指定硬體暫不可用",
        ["EncoderFallbackStartup"] = "硬體啟動失敗，使用 CPU",
        ["EncoderCpu"] = "CPU 軟體編碼 (libx264 相容穩定)",
        ["EncoderNvenc"] = "NVIDIA NVENC (硬體加速)",
        ["EncoderQsv"] = "Intel Quick Sync (QSV 硬體加速)",
        ["EncoderAmf"] = "AMD AMF (硬體加速)",
        ["DisplayChangedNotice"] = "偵測到螢幕解析度或顯示設定變更，已安全收斂停止並保存當前錄影。",
        ["WatchdogWarningNotice"] = "錄影寫入或影音管線出現遲滯，看門狗正全力維護錄影資料安全。",

        // 滑鼠游標效果
        ["CursorTitle"] = "游標樣式:",
        ["CursorDefault"] = "原始系統游標 (標準呈現)",
        ["CursorHighlight"] = "醒目黃色光圈 (教學推薦)",
        ["CursorClickRipple"] = "光圈 + 點擊波紋 (專業教學)",
        ["CursorHidden"] = "隱藏滑鼠游標 (不錄游標)",

        // 工具列與設定視窗
        ["Settings"] = "設定",
        ["TooltipSettings"] = "偏好設定與自訂快捷鍵 [快速鍵: F2]",
        ["SettingsTitle"] = "OpenCam 偏好設定",
        ["SettingsTabPreferencesNav"] = "偏好設定",
        ["SettingsTabAboutNav"] = "關於本程式",
        ["CloseButton"] = "關閉",
        ["SettingsTabHotkeys"] = "全域快捷鍵",
        ["SettingsTabGeneral"] = "一般與語言",
        ["SettingsTabQuality"] = "錄影品質與行為",
        ["SettingsTabStorage"] = "儲存與磁碟守護",

        // 快捷鍵自訂
        ["HotkeyStartStopLabel"] = "開始 / 停止錄影快捷鍵:",
        ["HotkeyPauseResumeLabel"] = "暫停 / 繼續錄影快捷鍵:",
        ["HotkeyModifierLabel"] = "修飾鍵:",
        ["HotkeyKeyLabel"] = "主按鍵:",
        ["HotkeyConflictError"] = "兩組快捷鍵不可完全相同，請重新配置！",
        ["HotkeyRegistrationFailed"] = "快捷鍵註冊失敗，可能已被其他應用程式佔用。",

        // 語言與介面
        ["LanguageLabel"] = "顯示語言 (Language):",
        ["LanguageOptionZhTw"] = "繁體中文 (Traditional Chinese)",
        ["LanguageOptionEnUs"] = "English (US)",

        // 畫質與行為
        ["VideoQualityLabel"] = "影片編碼畫質:",
        ["QualityUltra"] = "超高畫質（銳利清晰、檔案較大）",
        ["QualityStandard"] = "標準畫質（推薦平衡）",
        ["QualityCompact"] = "高壓縮節省空間（檔案較小）",
        ["OpenFolderOnFinishedLabel"] = "錄影停止並封裝完成後自動開啟目標資料夾",
        ["DeleteWorkingFileAfterRemuxLabel"] = "MP4 封裝完成後自動清理 MKV 工作檔",
        ["DeleteWorkingFileNotice"] = "安全提示：依專案高可靠規範，預設保留 MKV 原始檔以防外力損毀時能即時救援。",

        // 磁碟安全門檻
        ["DiskWarningThresholdLabel"] = "低剩餘空間警告門檻 (GB):",
        ["DiskCriticalThresholdLabel"] = "危急空間安全停止錄影門檻 (MB):",
        ["DiskThresholdNotice"] = "磁碟防護：當目標磁碟低於危急門檻時，OpenCam 會自動安全停止並保存已錄資料，防範硬碟塞滿崩潰。",

        // 設定按鈕與提示
        ["RecommendedTag"] = "推薦",
        ["SaveSettings"] = "儲存設定",
        ["ResetToDefaults"] = "還原預設值",
        ["SettingsSavedSuccess"] = "偏好設定已成功套用！"
    };

    public static readonly Dictionary<string, string> EnUsDictionary = new()
    {
        ["ProjectRestoreBackup"] = "Restore backup",
        ["ProjectRestoreWarning"] = "Restore the last valid backup? Newer edits may not be included. The damaged original will be preserved separately, and no source recordings will be deleted.",
        ["ProjectWorkspace"] = "Recording project",
        ["ProjectPreview"] = "Preview",
        ["ProjectFrameLoading"] = "Loading frame…",
        ["ProjectFrameEmpty"] = "Open a project with clips to preview",
        ["ProjectFrameUnavailable"] = "No frame at this position",
        ["ProjectStillPreview"] = "Source frame · No effects / audio playback",
        ["ProjectProperties"] = "Clip properties",
        ["ProjectTimeline"] = "Timeline",
        ["ProjectPreviewPending"] = "Video preview is not connected yet. Recording, saving, reopening and resuming are available. No demo footage is shown.",
        ["ProjectTimelinePending"] = "Timeline, thumbnails and audio waveforms are not connected yet. Original sources are retained.",
        ["ProjectEntryHint"] = "Save sources and continue later; MP4 export is optional",
        ["ProjectNew"] = "New project",
        ["ProjectOpen"] = "Open project",
        ["ProjectSave"] = "Save project",
        ["ProjectClose"] = "Close project",
        ["ProjectRecord"] = "Record new clip",
        ["ProjectContinue"] = "Continue recording",
        ["ProjectPause"] = "Pause & save",
        ["ProjectFinish"] = "Finish session",
        ["ProjectCaptureSettings"] = "Capture settings",
        ["ProjectClips"] = "Saved clips",
        ["ProjectClipLoadFailed"] = "Clip data is incomplete or has changed. Refresh before editing.",
        ["ProjectUndo"] = "Undo",
        ["ProjectRedo"] = "Redo",
        ["ProjectMoveEarlier"] = "Earlier",
        ["ProjectSplit"] = "Split",
        ["ProjectGroupNext"] = "Group with next",
        ["ProjectUngroup"] = "Ungroup",
        ["ProjectRangeStart"] = "Mark in",
        ["ProjectRangeEnd"] = "Mark out",
        ["ProjectDeleteRange"] = "Delete range",
        ["ProjectFitTimeline"] = "Fit timeline",
        ["ProjectWaveformLoading"] = "Loading waveform…",
        ["ProjectWaveformUnavailable"] = "Waveform unavailable",
        ["ProjectNoAudioTrack"] = "No audio track",
        ["ProjectTimelineHelp"] = "Click the ruler to seek; drag clip bodies to reorder or edges to trim. Scroll to pan, Ctrl/⌘ + scroll to zoom; Esc cancels.",
        ["ProjectMoveLater"] = "Later",
        ["ProjectDeleteClip"] = "Delete clip",
        ["ProjectClipName"] = "Clip name",
        ["ProjectAudioProperties"] = "Audio",
        ["ProjectVolume"] = "Volume (%)",
        ["ProjectMute"] = "Mute",
        ["ProjectFadeIn"] = "Fade in (s)",
        ["ProjectFadeOut"] = "Fade out (s)",
        ["ProjectVideoProperties"] = "Picture",
        ["ProjectScale"] = "Scale (%)",
        ["ProjectCrop"] = "Crop (%)",
        ["ProjectPositionX"] = "Horizontal offset (%)",
        ["ProjectPositionY"] = "Vertical offset (%)",
        ["ProjectApplyProperties"] = "Apply adjustments",
        ["ProjectPropertyDraft"] = "Apply or discard before switching clips. Saving also applies adjustments.",
        ["ProjectResetProperties"] = "Discard adjustments",
        ["ProjectInvalidProperties"] = "Check the clip name and values. Fades cannot exceed the clip duration.",
        ["ProjectRename"] = "Apply name",
        ["ProjectSourceSafe"] = "Edits never rewrite source media. Saving preserves this session’s undo/redo history.",
        ["ProjectPhaseBNotice"] = "This phase supports saving, reopening, continued recording and name undo. Timeline editing, video preview and MP4 export come next. Undo history does not persist across reopening.",
        ["ProjectRefresh"] = "Refresh status",
        ["ProjectRecent"] = "Recent projects",
        ["ProjectSaving"] = "Processing and saving…",
        ["ProjectSaved"] = "Saved",
        ["ProjectSaveFailed"] = "Operation incomplete. Review the error and retry.",
        ["ProjectUnsaved"] = "Unsaved changes",
        ["ProjectUnconfirmed"] = "Recorder status is unconfirmed; refresh before continuing.",
        ["ProjectFinishBeforeClose"] = "Finish and save the recording before closing the project. Recording will not be interrupted.",
        ["ProjectChooseFolder"] = "Choose the project location",
        ["ProjectDefaultName"] = "Recording project",
        ["ProjectModeClosed"] = "No project open",
        ["ProjectModeReady"] = "Ready",
        ["ProjectModeRecording"] = "Recording",
        ["ProjectModeSavingSegment"] = "Saving segment",
        ["ProjectModePaused"] = "Paused",
        ["ProjectModeSaveFailed"] = "Segment save failed",
        ["ProjectModeInterrupted"] = "Source or backup recovery required",
        // 視窗標題與通用
        ["AppTitle"] = "OpenCam - Screen Recorder",
        ["Confirm"] = "Confirm",
        ["Cancel"] = "Cancel",
        ["Close"] = "Close",

        // 頂部控制列
        ["StartRecording"] = "Record",
        ["StopRecording"] = "Stop",
        ["PauseRecording"] = "Pause",
        ["ResumeRecording"] = "Resume",
        ["OpenFolder"] = "Open Folder",
        ["Recovery"] = "Recovery",
        ["About"] = "About",
        ["Language"] = "Language",
        ["TooltipStart"] = "Start screen recording",
        ["TooltipStop"] = "Safely stop recording and remux to MP4",
        ["TooltipPause"] = "Pause screen recording",
        ["TooltipResume"] = "Resume screen recording",
        ["TooltipStartFormat"] = "Start screen recording [Hotkey: {0}]",
        ["TooltipStopFormat"] = "Safely stop recording and remux to MP4 [Hotkey: {0}]",
        ["TooltipPauseFormat"] = "Pause screen recording [Hotkey: {0}]",
        ["TooltipResumeFormat"] = "Resume screen recording [Hotkey: {0}]",
        ["TooltipFolder"] = "Open output recordings folder [Hotkey: Ctrl+O]",
        ["TooltipRecovery"] = "Scan and recover interrupted recording sessions",
        ["TooltipAbout"] = "About this application, author, and licenses [Hotkey: F1]",
        ["TooltipLanguage"] = "Switch interface language",

        // 準備中橫幅
        ["PreparingBanner"] = "Initializing recording pipeline and audio capture, please wait...",
        ["StartingBadge"] = "Starting...",

        // 錄影目標摘要
        ["TargetFullScreen"] = "Target: [Full Screen]",
        ["TargetMonitor"] = "Target: [Monitor - {0}]",
        ["TargetCustomRegion"] = "Target: [Custom Region - {0}x{1} (X:{2}, Y:{3})]",

        // 配置卡片
        ["ConfigTitle"] = "Recording Configuration",
        ["RangeTitle"] = "Capture Range",
        ["RangeFullScreen"] = "Full Screen",
        ["RangeMonitor"] = "Select Monitor:",
        ["IdentifyDisplays"] = "Identify displays",
        ["IdentifyDisplaysTooltip"] = "Briefly show the corresponding number on each display",
        ["DisplayIdentificationSelected"] = "Selected",
        ["DisplayIdentificationIncomplete"] = "Could not reliably identify {0} display(s); uncertain numbers were omitted.",
        ["RangeCustomRegion"] = "Custom Region",
        ["AdjustRegion"] = "Adjust Region...",
        ["TooltipAdjustRegion"] = "Drag or resize custom recording region [Enter: Confirm, ESC: Cancel]",
        ["FpsTitle"] = "Frame Rate (FPS):",
        ["AudioTitle"] = "Audio Settings",
        ["AudioSystem"] = "Record System Audio",
        ["AudioSystemUnsupportedMac"] = "macOS system audio (not supported in this version)",
        ["AudioMic"] = "Record Microphone",
        ["MicDevice"] = "Microphone Device:",
        ["StorageTitle"] = "Output Location",
        ["ChangeFolder"] = "Change...",
        ["TooltipChangeFolder"] = "Change output directory [Disk space updates automatically]",

        // 狀態監控儀表板
        ["MonitorTitle"] = "Status Monitor",
        ["AudioMeterSystem"] = "System audio",
        ["AudioMeterMicrophone"] = "Microphone",
        ["AudioMeterOff"] = "Off",
        ["AudioMeterLive"] = "Live",
        ["AudioMeterSilent"] = "Silent",
        ["AudioMeterPaused"] = "Paused",
        ["AudioMeterUnavailable"] = "Unavailable",
        ["StatusIdle"] = "IDLE",
        ["StatusRecording"] = "RECORDING",
        ["StatusPaused"] = "PAUSED",
        ["StatusPreparing"] = "PREPARING",
        ["FileSizeLabel"] = "File Size",
        ["DiskRemainingLabel"] = "Available Disk",
        ["SafeContainerNotice"] = "Safe MKV Continuous Write · Lossless Remux MP4",

        // 狀態列動態訊息
        ["StatusReady"] = "Ready. Click 'Record' to start capturing.",
        ["StatusInitializing"] = "Initializing recording pipeline, please wait...",
        ["StatusStartUnconfirmed"] = "Recording startup is not yet confirmed. Keep OpenCam open, or press Stop to end it safely.",
        ["StatusScreenPermissionRequired"] = "macOS screen-recording permission is required. Allow OpenCam in System Settings > Privacy & Security > Screen & System Audio Recording, then restart the app.",
        ["StatusRecordingActive"] = "Recording in progress (Continuous write to safe MKV)",
        ["StatusDiskSpaceWarning"] = "Low disk space: {0:F1} GB remaining. Recording will stop safely at the critical threshold.",
        ["StatusRecorderHealthWarning"] = "Recorder health warning: {0}",
        ["StatusRecorderStoppedUnexpectedly"] = "Recording stopped unexpectedly: {0}",
        ["StatusPausedMsg"] = "Recording paused. Click 'Resume' to continue.",
        ["StatusResuming"] = "Resuming recording pipeline, please wait...",
        ["StatusStopping"] = "Safely closing MKV and performing lossless MP4 remux...",
        ["StatusSuccess"] = "Recording finished! MP4 file exported successfully.",
        ["StatusFailed"] = "Failed to start: {0}",
        ["StatusStopFailed"] = "Failed to stop: {0}",
        ["StatusRecoverableDetected"] = "Detected {0} interrupted session(s)! Click 'Recovery' to export to MP4.",
        ["StatusNoRecoverable"] = "No interrupted recording sessions found.",
        ["StatusRecovering"] = "Performing session crash recovery, please wait...",
        ["StatusRecoverSuccess"] = "Recovery completed! Successfully restored {0} session(s) to MP4.",
        ["StatusRecoverPartial"] = "Recovery completed: {0} fully recovered, {1} partially recovered, and {2} failed. Partial results may omit a damaged tail; all original MKV files were preserved.",
        ["StatusRecoverFailed"] = "Recovery failed for {0} session(s). Original MKV files were preserved; check the logs for details.",
        ["StatusLocationUpdated"] = "Storage location updated to: {0}",
        ["StatusSetLocationFailed"] = "Failed to update storage directory: {0}",
        ["StatusOpenFolderFailed"] = "Unable to open the output location: {0}",
        ["StatusUnexpectedDisconnect"] = "Recording core disconnected! Captured data safely preserved. Click 'Recovery' to export MP4.",
        ["RecordingCloseWarningTitle"] = "Recording in Progress",
        ["RecordingCloseWarningMessage"] = "Stop the recording before closing OpenCam.",
        ["RecordingCloseWarningDetail"] = "The close request was canceled and recording will continue.",
        ["ReturnToRecording"] = "Return to Recording",
        ["RecordingCloseUnconfirmedMessage"] = "Recording status is unknown and a safe stop did not succeed.",
        ["RecordingCloseUnconfirmedDetail"] = "Keep OpenCam open and wait, or force quit. Force quitting may interrupt the video and require recovery.",
        ["ForceQuitButton"] = "Force Quit…",
        ["ForceQuitConfirmTitle"] = "Confirm Force Quit",
        ["ForceQuitConfirmMessage"] = "This immediately closes OpenCam and its recorder. The unfinished MKV may need recovery.",
        ["ForceQuitConfirmDetail"] = "Use only when safe stop failed and recording status cannot be confirmed. This cannot be undone.",
        ["ForceQuitCancel"] = "Cancel and Keep Open",
        ["ForceQuitConfirmAction"] = "Confirm Force Quit",
        ["VersionAndAbout"] = "OpenCam {0} · About",

        // 關於視窗
        ["AboutTitle"] = "About OpenCam",
        ["AppName"] = "OpenCam",
        ["VersionLabel"] = "Version: {0}",
        ["AuthorLabel"] = "Author:",
        ["AuthorName"] = "Yu-Han Cheng (鄭郁翰)",
        ["GithubLabel"] = "GitHub Project",
        ["ProjectLicenseLabel"] = "Project license:",
        ["ProjectLicenseName"] = "AGPL-3.0-or-later",
        ["ProjectLicenseDetail"] = "OpenCam source is licensed under GNU AGPL version 3 or later. See LICENSE in the GitHub repository for the full terms and source code. Provided without warranty. Third-party components retain their own licenses.",
        ["AppDescription"] = "A simple, stable, and highly reliable desktop screen recording tool.\nKey Features: Continuous MKV safe container writing, lossless MP4 remuxing on graceful stop, crash and power-loss recovery, full/multi-monitor/custom region capture, and precise A/V sync.",
        ["ThirdPartyTitle"] = "Major Third-Party Components",
        ["LicenseFfmpegDesc"] = "Official packages use GPL-enabled FFmpeg/ffprobe, including libx264. See the bundled notices for the exact license, build configuration and source information. These are not OpenCam-owned sources.",
        ["LicenseAvaloniaDesc"] = "The AvaloniaUI Project; upstream license: Copyright (c) AvaloniaUI OÜ. MIT License, with upstream third-party notices retained.",
        ["LicenseMvvmDesc"] = "Copyright (c) .NET Foundation and Contributors. Licensed under the MIT License.",
        ["LicenseSerilogDesc"] = "Copyright (c) Serilog Contributors. Licensed under the Apache License 2.0.",
        ["LicenseXunitDesc"] = "Copyright (c) .NET Foundation and Contributors. Licensed under the Apache License 2.0.",
        ["LicenseOtherManagedDesc"] = "NAudio (Mark Heath), MicroCom.Runtime (Nikita Tsukanov), Tmds.DBus.Protocol (Tom Deseyn), and Microsoft .NET/Extensions components: MIT. See bundled notices for full attribution.",
        ["LicenseGraphicsDesc"] = "SkiaSharp/HarfBuzzSharp managed wrappers: MIT. Native Skia, HarfBuzz, ANGLE and their dependencies retain their own terms; full upstream licenses and notices are included.",
        ["LicenseInterDesc"] = "Copyright 2020 The Inter Project Authors. Inter 3.019 fonts bundled by Avalonia.Fonts.Inter: SIL Open Font License 1.1.",
        ["ThirdPartyNoticesDetail"] = "See THIRD-PARTY-NOTICES.md and the third-party folder (Windows: installation directory; macOS: Contents/Resources inside the app). Third-party licenses are not replaced by OpenCam's AGPL-3.0-or-later license.",
        ["HotkeyCloseTip"] = "Press ESC or Enter to close",
        ["AboutReliabilityTitle"] = "Reliability First",
        ["DisclaimerTitle"] = "Disclaimer & Terms of Use",
        ["Disclaimer1Title"] = "1. No Warranty: ",
        ["Disclaimer1Text"] = "This software is provided 'AS IS', without any express or implied warranties, including but not limited to the implied warranties of merchantability and fitness for a particular purpose.",
        ["Disclaimer2Title"] = "2. Assumption of Risk: ",
        ["Disclaimer2Text"] = "The user assumes all risks associated with the use of this software.",
        ["Disclaimer3Title"] = "3. Limitation of Liability: ",
        ["Disclaimer3Text"] = "The authors shall not be liable for any damages arising out of the use of this software, including loss of data.",
        ["Disclaimer4Title"] = "4. Legal Compliance: ",
        ["Disclaimer4Text"] = "Users are responsible for ensuring compliance with their local privacy and security laws when recording.",

        // 選區視窗
        ["RegionWindowTitle"] = "Select Recording Region",
        ["RegionFitScreen"] = "Fit Screen",
        ["TooltipRegionFitScreen"] = "Quickly expand selection to fit the entire current screen",
        ["RegionConfirm"] = "Confirm (Enter)",
        ["RegionCancel"] = "Cancel (ESC)",
        ["RegionDragTip"] = "Drag inside area to move capture region",
        ["RegionResizeTip"] = "Drag borders or corners to resize | ESC to cancel | Enter or double-click to confirm",
        ["RegionSizeFormat"] = "Size: {0} x {1} (Pos X:{2}, Y:{3})",
        ["MonitorPrimaryFormat"] = "Monitor {0} (Primary)",
        ["MonitorSecondaryFormat"] = "Monitor {0} (Secondary)",
        ["DefaultMicOption"] = "Default System Microphone",

        // 系統托盤與偏好設定
        ["MinimizeOnRecord"] = "Minimize window when recording starts",
        ["TrayShowWindow"] = "Show Window",
        ["TrayStart"] = "Start Recording",
        ["TrayStop"] = "Stop Recording",
        ["TrayExit"] = "Exit",

        // 視訊編碼器與硬體加速
        ["EncoderTitle"] = "Video Encoder:",
        ["EncoderAuto"] = "Auto (Hardware Accelerated)",
        ["ActualEncoderPending"] = "Actual encoder: pending",
        ["ActualCapturePending"] = "Actual capture: pending",
        ["ActualCaptureFormat"] = "Actual capture: {0}",
        ["CaptureModeLabel"] = "Windows screen capture",
        ["CaptureModeGdi"] = "Compatible capture (GDI)",
        ["CaptureModeModern"] = "Modern capture (experimental)",
        ["CaptureModeNotice"] = "May help cursor flicker on some PCs; not a confirmed fix. Unsupported display configurations use GDI. Check the actual capture status.",
        ["CaptureFallbackFilter"] = "Required FFmpeg capture capability unavailable",
        ["CaptureFallbackMapping"] = "Display cannot be safely mapped",
        ["CaptureFallbackTopology"] = "Display configuration requires compatible capture",
        ["CaptureFallbackStartup"] = "Modern capture startup failed; using GDI",
        ["ActualEncoderFormat"] = "Actual encoder: {0}",
        ["EncoderFallbackNoHardware"] = "No validated hardware encoder",
        ["EncoderFallbackRequested"] = "Requested hardware unavailable",
        ["EncoderFallbackStartup"] = "Hardware startup failed; using CPU",
        ["EncoderCpu"] = "CPU Software (libx264 Compatible)",
        ["EncoderNvenc"] = "NVIDIA NVENC (Hardware)",
        ["EncoderQsv"] = "Intel Quick Sync (QSV Hardware)",
        ["EncoderAmf"] = "AMD AMF (Hardware)",
        ["DisplayChangedNotice"] = "Display settings changed. Current recording safely finalized and saved.",
        ["WatchdogWarningNotice"] = "Recording write latency detected. Watchdog is safeguarding stream data.",

        // 滑鼠游標效果
        ["CursorTitle"] = "Mouse Cursor:",
        ["CursorDefault"] = "Default System Cursor",
        ["CursorHighlight"] = "Highlight Halo (Recommended)",
        ["CursorClickRipple"] = "Halo + Click Ripple (Tutorial)",
        ["CursorHidden"] = "Hide Cursor (Clean View)",

        // Toolbar & Settings Window
        ["Settings"] = "Settings",
        ["TooltipSettings"] = "Preferences and Custom Hotkeys [Hotkey: F2]",
        ["SettingsTitle"] = "OpenCam Preferences",
        ["SettingsTabPreferencesNav"] = "Preferences",
        ["SettingsTabAboutNav"] = "About OpenCam",
        ["CloseButton"] = "Close",
        ["SettingsTabHotkeys"] = "Global Hotkeys",
        ["SettingsTabGeneral"] = "General & Language",
        ["SettingsTabQuality"] = "Video Quality & Actions",
        ["SettingsTabStorage"] = "Storage & Disk Guard",

        // Hotkeys Customization
        ["HotkeyStartStopLabel"] = "Start / Stop Recording Hotkey:",
        ["HotkeyPauseResumeLabel"] = "Pause / Resume Recording Hotkey:",
        ["HotkeyModifierLabel"] = "Modifier:",
        ["HotkeyKeyLabel"] = "Key:",
        ["HotkeyConflictError"] = "Hotkeys cannot be identical. Please choose distinct keys!",
        ["HotkeyRegistrationFailed"] = "Failed to register hotkey. It may be in use by another application.",

        // Language & UI
        ["LanguageLabel"] = "Display Language:",
        ["LanguageOptionZhTw"] = "繁體中文 (Traditional Chinese)",
        ["LanguageOptionEnUs"] = "English (US)",

        // Quality & Actions
        ["VideoQualityLabel"] = "Video Encoding Quality:",
        ["QualityUltra"] = "Ultra Quality (sharper, larger files)",
        ["QualityStandard"] = "Standard Quality (recommended balance)",
        ["QualityCompact"] = "Compact Size (smaller files)",
        ["OpenFolderOnFinishedLabel"] = "Automatically open destination folder when recording finishes",
        ["DeleteWorkingFileAfterRemuxLabel"] = "Automatically clean up MKV working file after MP4 remux",
        ["DeleteWorkingFileNotice"] = "Safety Notice: By default, keeping MKV ensures maximum crash recovery capability.",

        // Disk Protection
        ["DiskWarningThresholdLabel"] = "Low Disk Space Warning Threshold (GB):",
        ["DiskCriticalThresholdLabel"] = "Critical Disk Space Auto-Stop Threshold (MB):",
        ["DiskThresholdNotice"] = "Disk Protection: OpenCam automatically stops and finalizes recording when disk space is critically low.",

        // Buttons & Messages
        ["RecommendedTag"] = "Recommended",
        ["SaveSettings"] = "Save Settings",
        ["ResetToDefaults"] = "Restore Defaults",
        ["SettingsSavedSuccess"] = "Preferences applied successfully!"
    };
}
